site_name: hamiumʷⁱᵏⁱ
copyright: Copyright &copy; 2023 - 2024 hamium
repo_url: https://github.com/hamium/factions-wiki
nav:
  - Home: index.md
  - Factions (Season 4):
      - CIA: factions/cia.md
      - Areial Empire: factions/ae.md
      - Sky Crew: factions/sc.md
      - Banana Syndicate: factions/bs.md
      - Greenie Company: factions/gc.md
      - Internet Explorers: factions/ie.md
  - Structures (Season 4):
      - Spawn: structures/spawn_s4.md
      - Tavern Complex: structures/tavern_complex_s4.md
      - History Gazette HQ: structures/historygazette_hq_s4.md
  - Notable players:
      - Staff:
          - LeUnium: staff/unium.md
          - ham_: staff/ham.md
          - Slimsiomai: staff/slim.md
          - Reguleo: staff/leo.md
          - Hydra72: staff/hydra.md
          - kaeud_: staff/kaeud.md
          - claniverse: staff/realclay.md
          - Targaros: staff/targ.md
          - ajipotato: staff/aji.md
          - mireu: staff/mireu.md
      - Regular players:
          - ItzSKP: players/itzskp.md
          - Hades: players/hades.md
          - MinoCP: players/minocp.md
  - Events:
      - Marriage (Aji & Mireu): events/1.md
  - Seasons:
      - Season 1: seasons/s1.md
      - Season 2: seasons/s2.md
      - Season 3: seasons/s3.md
      - Season 4 (current): seasons/s4.md
  - Extra:
      - hamiumᵐᵐᵒ: extra/hamiummmo.md
      - hamerMC: extra/hammermc.md
      - hammerDiscord: extra/hammerdc.md
      - Racks: extra/racks.md
  - List of staff: staff.md

theme:
  name: material
  logo: assets/imgs/logo.png
  favicon: assets/imgs/logo.png
  font:
    text: Open Sans
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - header.autohide
    - navigation.footer
    - navigation.instant

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hamium
    - icon: fontawesome/brands/discord
      link: https://discord.gg/h2PnjPHxNP

extra_css:
  - assets/stylesheets/colors.css
